/* Detray library, part of the ACTS project (R&D line)
 *
 * (c) 2025 CERN for the benefit of the ACTS project
 *
 * Mozilla Public License Version 2.0
 *
 * Note: This file is automatically generated.
 *       Do not modify it manually.
 *
 * Modified: Added DETRAY_MIXED_PRECISION_COVARIANCE option for FP32 stability
 */

#pragma once

#include "detray/definitions/algebra.hpp"
#include "detray/definitions/detail/qualifiers.hpp"

namespace detray::detail {

#ifdef DETRAY_MIXED_PRECISION_COVARIANCE

// Mixed-precision version: computes J * C * J^T in double precision
// to avoid accumulation of rounding errors in FP32 builds
template <typename jac_matrix_t, typename cov_matrix_t>
DETRAY_HOST_DEVICE void inline transport_covariance_to_bound_impl(
    const cov_matrix_t& C, const jac_matrix_t& J_full, cov_matrix_t& new_C) {

    // Helper macros to get matrix elements as double
    #define GET_C_D(i, j) static_cast<double>(getter::element(C, i##u, j##u))
    #define GET_J_D(i, j) static_cast<double>(getter::element(J_full, i##u, j##u))

    // Compute intermediate values in double precision (C * J^T columns)
    const double x4 = GET_C_D(4, 4) * GET_J_D(0, 4);
    const double x10 = GET_C_D(4, 4) * GET_J_D(1, 4);
    const double x16 = GET_C_D(4, 4) * GET_J_D(2, 4);
    const double x22 = GET_C_D(4, 4) * GET_J_D(3, 4);
    const double x24 = GET_C_D(4, 4) * GET_J_D(5, 4);

    const double x0 = GET_C_D(0, 0) * GET_J_D(0, 0) +
                      GET_C_D(1, 0) * GET_J_D(0, 1) +
                      GET_C_D(2, 0) * GET_J_D(0, 2) +
                      GET_C_D(3, 0) * GET_J_D(0, 3) +
                      GET_C_D(4, 0) * GET_J_D(0, 4);
    const double x1 = GET_C_D(0, 1) * GET_J_D(0, 0) +
                      GET_C_D(1, 1) * GET_J_D(0, 1) +
                      GET_C_D(2, 1) * GET_J_D(0, 2) +
                      GET_C_D(3, 1) * GET_J_D(0, 3) +
                      GET_C_D(4, 1) * GET_J_D(0, 4);
    const double x2 = GET_C_D(0, 2) * GET_J_D(0, 0) +
                      GET_C_D(1, 2) * GET_J_D(0, 1) +
                      GET_C_D(2, 2) * GET_J_D(0, 2) +
                      GET_C_D(3, 2) * GET_J_D(0, 3) +
                      GET_C_D(4, 2) * GET_J_D(0, 4);
    const double x3 = GET_C_D(0, 3) * GET_J_D(0, 0) +
                      GET_C_D(1, 3) * GET_J_D(0, 1) +
                      GET_C_D(2, 3) * GET_J_D(0, 2) +
                      GET_C_D(3, 3) * GET_J_D(0, 3) +
                      GET_C_D(4, 3) * GET_J_D(0, 4);
    const double x6 = GET_C_D(0, 0) * GET_J_D(1, 0) +
                      GET_C_D(1, 0) * GET_J_D(1, 1) +
                      GET_C_D(2, 0) * GET_J_D(1, 2) +
                      GET_C_D(3, 0) * GET_J_D(1, 3) +
                      GET_C_D(4, 0) * GET_J_D(1, 4);
    const double x7 = GET_C_D(0, 1) * GET_J_D(1, 0) +
                      GET_C_D(1, 1) * GET_J_D(1, 1) +
                      GET_C_D(2, 1) * GET_J_D(1, 2) +
                      GET_C_D(3, 1) * GET_J_D(1, 3) +
                      GET_C_D(4, 1) * GET_J_D(1, 4);
    const double x8 = GET_C_D(0, 2) * GET_J_D(1, 0) +
                      GET_C_D(1, 2) * GET_J_D(1, 1) +
                      GET_C_D(2, 2) * GET_J_D(1, 2) +
                      GET_C_D(3, 2) * GET_J_D(1, 3) +
                      GET_C_D(4, 2) * GET_J_D(1, 4);
    const double x9 = GET_C_D(0, 3) * GET_J_D(1, 0) +
                      GET_C_D(1, 3) * GET_J_D(1, 1) +
                      GET_C_D(2, 3) * GET_J_D(1, 2) +
                      GET_C_D(3, 3) * GET_J_D(1, 3) +
                      GET_C_D(4, 3) * GET_J_D(1, 4);
    const double x12 = GET_C_D(0, 0) * GET_J_D(2, 0) +
                       GET_C_D(1, 0) * GET_J_D(2, 1) +
                       GET_C_D(2, 0) * GET_J_D(2, 2) +
                       GET_C_D(3, 0) * GET_J_D(2, 3) +
                       GET_C_D(4, 0) * GET_J_D(2, 4);
    const double x13 = GET_C_D(0, 1) * GET_J_D(2, 0) +
                       GET_C_D(1, 1) * GET_J_D(2, 1) +
                       GET_C_D(2, 1) * GET_J_D(2, 2) +
                       GET_C_D(3, 1) * GET_J_D(2, 3) +
                       GET_C_D(4, 1) * GET_J_D(2, 4);
    const double x14 = GET_C_D(0, 2) * GET_J_D(2, 0) +
                       GET_C_D(1, 2) * GET_J_D(2, 1) +
                       GET_C_D(2, 2) * GET_J_D(2, 2) +
                       GET_C_D(3, 2) * GET_J_D(2, 3) +
                       GET_C_D(4, 2) * GET_J_D(2, 4);
    const double x15 = GET_C_D(0, 3) * GET_J_D(2, 0) +
                       GET_C_D(1, 3) * GET_J_D(2, 1) +
                       GET_C_D(2, 3) * GET_J_D(2, 2) +
                       GET_C_D(3, 3) * GET_J_D(2, 3) +
                       GET_C_D(4, 3) * GET_J_D(2, 4);
    const double x18 = GET_C_D(0, 0) * GET_J_D(3, 0) +
                       GET_C_D(1, 0) * GET_J_D(3, 1) +
                       GET_C_D(2, 0) * GET_J_D(3, 2) +
                       GET_C_D(3, 0) * GET_J_D(3, 3) +
                       GET_C_D(4, 0) * GET_J_D(3, 4);
    const double x19 = GET_C_D(0, 1) * GET_J_D(3, 0) +
                       GET_C_D(1, 1) * GET_J_D(3, 1) +
                       GET_C_D(2, 1) * GET_J_D(3, 2) +
                       GET_C_D(3, 1) * GET_J_D(3, 3) +
                       GET_C_D(4, 1) * GET_J_D(3, 4);
    const double x20 = GET_C_D(0, 2) * GET_J_D(3, 0) +
                       GET_C_D(1, 2) * GET_J_D(3, 1) +
                       GET_C_D(2, 2) * GET_J_D(3, 2) +
                       GET_C_D(3, 2) * GET_J_D(3, 3) +
                       GET_C_D(4, 2) * GET_J_D(3, 4);
    const double x21 = GET_C_D(0, 3) * GET_J_D(3, 0) +
                       GET_C_D(1, 3) * GET_J_D(3, 1) +
                       GET_C_D(2, 3) * GET_J_D(3, 2) +
                       GET_C_D(3, 3) * GET_J_D(3, 3) +
                       GET_C_D(4, 3) * GET_J_D(3, 4);
    const double x25 = GET_C_D(0, 0) * GET_J_D(5, 0) +
                       GET_C_D(1, 0) * GET_J_D(5, 1) +
                       GET_C_D(2, 0) * GET_J_D(5, 2) +
                       GET_C_D(3, 0) * GET_J_D(5, 3) +
                       GET_C_D(4, 0) * GET_J_D(5, 4) +
                       GET_C_D(5, 0);
    const double x26 = GET_C_D(0, 1) * GET_J_D(5, 0) +
                       GET_C_D(1, 1) * GET_J_D(5, 1) +
                       GET_C_D(2, 1) * GET_J_D(5, 2) +
                       GET_C_D(3, 1) * GET_J_D(5, 3) +
                       GET_C_D(4, 1) * GET_J_D(5, 4) +
                       GET_C_D(5, 1);
    const double x27 = GET_C_D(0, 2) * GET_J_D(5, 0) +
                       GET_C_D(1, 2) * GET_J_D(5, 1) +
                       GET_C_D(2, 2) * GET_J_D(5, 2) +
                       GET_C_D(3, 2) * GET_J_D(5, 3) +
                       GET_C_D(4, 2) * GET_J_D(5, 4) +
                       GET_C_D(5, 2);
    const double x28 = GET_C_D(0, 3) * GET_J_D(5, 0) +
                       GET_C_D(1, 3) * GET_J_D(5, 1) +
                       GET_C_D(2, 3) * GET_J_D(5, 2) +
                       GET_C_D(3, 3) * GET_J_D(5, 3) +
                       GET_C_D(4, 3) * GET_J_D(5, 4) +
                       GET_C_D(5, 3);
    const double x5 = x4 + GET_C_D(0, 4) * GET_J_D(0, 0) +
                      GET_C_D(1, 4) * GET_J_D(0, 1) +
                      GET_C_D(2, 4) * GET_J_D(0, 2) +
                      GET_C_D(3, 4) * GET_J_D(0, 3);
    const double x11 = x10 + GET_C_D(0, 4) * GET_J_D(1, 0) +
                       GET_C_D(1, 4) * GET_J_D(1, 1) +
                       GET_C_D(2, 4) * GET_J_D(1, 2) +
                       GET_C_D(3, 4) * GET_J_D(1, 3);
    const double x17 = x16 + GET_C_D(0, 4) * GET_J_D(2, 0) +
                       GET_C_D(1, 4) * GET_J_D(2, 1) +
                       GET_C_D(2, 4) * GET_J_D(2, 2) +
                       GET_C_D(3, 4) * GET_J_D(2, 3);
    const double x23 = x22 + GET_C_D(0, 4) * GET_J_D(3, 0) +
                       GET_C_D(1, 4) * GET_J_D(3, 1) +
                       GET_C_D(2, 4) * GET_J_D(3, 2) +
                       GET_C_D(3, 4) * GET_J_D(3, 3);
    const double x29 = x24 + GET_C_D(0, 4) * GET_J_D(5, 0) +
                       GET_C_D(1, 4) * GET_J_D(5, 1) +
                       GET_C_D(2, 4) * GET_J_D(5, 2) +
                       GET_C_D(3, 4) * GET_J_D(5, 3) +
                       GET_C_D(5, 4);

    // Compute final result and cast back to native scalar type
    using scalar_t = std::decay_t<decltype(getter::element(new_C, 0u, 0u))>;

    getter::element(new_C, 0u, 0u) = static_cast<scalar_t>(
        x0 * GET_J_D(0, 0) + x1 * GET_J_D(0, 1) +
        x2 * GET_J_D(0, 2) + x3 * GET_J_D(0, 3) +
        x5 * GET_J_D(0, 4));
    getter::element(new_C, 1u, 0u) = static_cast<scalar_t>(
        x11 * GET_J_D(0, 4) + x6 * GET_J_D(0, 0) +
        x7 * GET_J_D(0, 1) + x8 * GET_J_D(0, 2) +
        x9 * GET_J_D(0, 3));
    getter::element(new_C, 2u, 0u) = static_cast<scalar_t>(
        x12 * GET_J_D(0, 0) + x13 * GET_J_D(0, 1) +
        x14 * GET_J_D(0, 2) + x15 * GET_J_D(0, 3) +
        x17 * GET_J_D(0, 4));
    getter::element(new_C, 3u, 0u) = static_cast<scalar_t>(
        x18 * GET_J_D(0, 0) + x19 * GET_J_D(0, 1) +
        x20 * GET_J_D(0, 2) + x21 * GET_J_D(0, 3) +
        x23 * GET_J_D(0, 4));
    getter::element(new_C, 4u, 0u) = static_cast<scalar_t>(
        x4 + GET_C_D(4, 0) * GET_J_D(0, 0) +
        GET_C_D(4, 1) * GET_J_D(0, 1) +
        GET_C_D(4, 2) * GET_J_D(0, 2) +
        GET_C_D(4, 3) * GET_J_D(0, 3));
    getter::element(new_C, 5u, 0u) = static_cast<scalar_t>(
        x25 * GET_J_D(0, 0) + x26 * GET_J_D(0, 1) +
        x27 * GET_J_D(0, 2) + x28 * GET_J_D(0, 3) +
        x29 * GET_J_D(0, 4));
    getter::element(new_C, 0u, 1u) = static_cast<scalar_t>(
        x0 * GET_J_D(1, 0) + x1 * GET_J_D(1, 1) +
        x2 * GET_J_D(1, 2) + x3 * GET_J_D(1, 3) +
        x5 * GET_J_D(1, 4));
    getter::element(new_C, 1u, 1u) = static_cast<scalar_t>(
        x11 * GET_J_D(1, 4) + x6 * GET_J_D(1, 0) +
        x7 * GET_J_D(1, 1) + x8 * GET_J_D(1, 2) +
        x9 * GET_J_D(1, 3));
    getter::element(new_C, 2u, 1u) = static_cast<scalar_t>(
        x12 * GET_J_D(1, 0) + x13 * GET_J_D(1, 1) +
        x14 * GET_J_D(1, 2) + x15 * GET_J_D(1, 3) +
        x17 * GET_J_D(1, 4));
    getter::element(new_C, 3u, 1u) = static_cast<scalar_t>(
        x18 * GET_J_D(1, 0) + x19 * GET_J_D(1, 1) +
        x20 * GET_J_D(1, 2) + x21 * GET_J_D(1, 3) +
        x23 * GET_J_D(1, 4));
    getter::element(new_C, 4u, 1u) = static_cast<scalar_t>(
        x10 + GET_C_D(4, 0) * GET_J_D(1, 0) +
        GET_C_D(4, 1) * GET_J_D(1, 1) +
        GET_C_D(4, 2) * GET_J_D(1, 2) +
        GET_C_D(4, 3) * GET_J_D(1, 3));
    getter::element(new_C, 5u, 1u) = static_cast<scalar_t>(
        x25 * GET_J_D(1, 0) + x26 * GET_J_D(1, 1) +
        x27 * GET_J_D(1, 2) + x28 * GET_J_D(1, 3) +
        x29 * GET_J_D(1, 4));
    getter::element(new_C, 0u, 2u) = static_cast<scalar_t>(
        x0 * GET_J_D(2, 0) + x1 * GET_J_D(2, 1) +
        x2 * GET_J_D(2, 2) + x3 * GET_J_D(2, 3) +
        x5 * GET_J_D(2, 4));
    getter::element(new_C, 1u, 2u) = static_cast<scalar_t>(
        x11 * GET_J_D(2, 4) + x6 * GET_J_D(2, 0) +
        x7 * GET_J_D(2, 1) + x8 * GET_J_D(2, 2) +
        x9 * GET_J_D(2, 3));
    getter::element(new_C, 2u, 2u) = static_cast<scalar_t>(
        x12 * GET_J_D(2, 0) + x13 * GET_J_D(2, 1) +
        x14 * GET_J_D(2, 2) + x15 * GET_J_D(2, 3) +
        x17 * GET_J_D(2, 4));
    getter::element(new_C, 3u, 2u) = static_cast<scalar_t>(
        x18 * GET_J_D(2, 0) + x19 * GET_J_D(2, 1) +
        x20 * GET_J_D(2, 2) + x21 * GET_J_D(2, 3) +
        x23 * GET_J_D(2, 4));
    getter::element(new_C, 4u, 2u) = static_cast<scalar_t>(
        x16 + GET_C_D(4, 0) * GET_J_D(2, 0) +
        GET_C_D(4, 1) * GET_J_D(2, 1) +
        GET_C_D(4, 2) * GET_J_D(2, 2) +
        GET_C_D(4, 3) * GET_J_D(2, 3));
    getter::element(new_C, 5u, 2u) = static_cast<scalar_t>(
        x25 * GET_J_D(2, 0) + x26 * GET_J_D(2, 1) +
        x27 * GET_J_D(2, 2) + x28 * GET_J_D(2, 3) +
        x29 * GET_J_D(2, 4));
    getter::element(new_C, 0u, 3u) = static_cast<scalar_t>(
        x0 * GET_J_D(3, 0) + x1 * GET_J_D(3, 1) +
        x2 * GET_J_D(3, 2) + x3 * GET_J_D(3, 3) +
        x5 * GET_J_D(3, 4));
    getter::element(new_C, 1u, 3u) = static_cast<scalar_t>(
        x11 * GET_J_D(3, 4) + x6 * GET_J_D(3, 0) +
        x7 * GET_J_D(3, 1) + x8 * GET_J_D(3, 2) +
        x9 * GET_J_D(3, 3));
    getter::element(new_C, 2u, 3u) = static_cast<scalar_t>(
        x12 * GET_J_D(3, 0) + x13 * GET_J_D(3, 1) +
        x14 * GET_J_D(3, 2) + x15 * GET_J_D(3, 3) +
        x17 * GET_J_D(3, 4));
    getter::element(new_C, 3u, 3u) = static_cast<scalar_t>(
        x18 * GET_J_D(3, 0) + x19 * GET_J_D(3, 1) +
        x20 * GET_J_D(3, 2) + x21 * GET_J_D(3, 3) +
        x23 * GET_J_D(3, 4));
    getter::element(new_C, 4u, 3u) = static_cast<scalar_t>(
        x22 + GET_C_D(4, 0) * GET_J_D(3, 0) +
        GET_C_D(4, 1) * GET_J_D(3, 1) +
        GET_C_D(4, 2) * GET_J_D(3, 2) +
        GET_C_D(4, 3) * GET_J_D(3, 3));
    getter::element(new_C, 5u, 3u) = static_cast<scalar_t>(
        x25 * GET_J_D(3, 0) + x26 * GET_J_D(3, 1) +
        x27 * GET_J_D(3, 2) + x28 * GET_J_D(3, 3) +
        x29 * GET_J_D(3, 4));
    getter::element(new_C, 0u, 4u) = static_cast<scalar_t>(x5);
    getter::element(new_C, 1u, 4u) = static_cast<scalar_t>(x11);
    getter::element(new_C, 2u, 4u) = static_cast<scalar_t>(x17);
    getter::element(new_C, 3u, 4u) = static_cast<scalar_t>(x23);
    getter::element(new_C, 4u, 4u) = static_cast<scalar_t>(GET_C_D(4, 4));
    getter::element(new_C, 5u, 4u) = static_cast<scalar_t>(x29);
    getter::element(new_C, 0u, 5u) = static_cast<scalar_t>(
        x0 * GET_J_D(5, 0) + x1 * GET_J_D(5, 1) +
        x2 * GET_J_D(5, 2) + x3 * GET_J_D(5, 3) +
        x5 * GET_J_D(5, 4) +
        GET_C_D(0, 5) * GET_J_D(0, 0) +
        GET_C_D(1, 5) * GET_J_D(0, 1) +
        GET_C_D(2, 5) * GET_J_D(0, 2) +
        GET_C_D(3, 5) * GET_J_D(0, 3) +
        GET_C_D(4, 5) * GET_J_D(0, 4));
    getter::element(new_C, 1u, 5u) = static_cast<scalar_t>(
        x11 * GET_J_D(5, 4) + x6 * GET_J_D(5, 0) +
        x7 * GET_J_D(5, 1) + x8 * GET_J_D(5, 2) +
        x9 * GET_J_D(5, 3) +
        GET_C_D(0, 5) * GET_J_D(1, 0) +
        GET_C_D(1, 5) * GET_J_D(1, 1) +
        GET_C_D(2, 5) * GET_J_D(1, 2) +
        GET_C_D(3, 5) * GET_J_D(1, 3) +
        GET_C_D(4, 5) * GET_J_D(1, 4));
    getter::element(new_C, 2u, 5u) = static_cast<scalar_t>(
        x12 * GET_J_D(5, 0) + x13 * GET_J_D(5, 1) +
        x14 * GET_J_D(5, 2) + x15 * GET_J_D(5, 3) +
        x17 * GET_J_D(5, 4) +
        GET_C_D(0, 5) * GET_J_D(2, 0) +
        GET_C_D(1, 5) * GET_J_D(2, 1) +
        GET_C_D(2, 5) * GET_J_D(2, 2) +
        GET_C_D(3, 5) * GET_J_D(2, 3) +
        GET_C_D(4, 5) * GET_J_D(2, 4));
    getter::element(new_C, 3u, 5u) = static_cast<scalar_t>(
        x18 * GET_J_D(5, 0) + x19 * GET_J_D(5, 1) +
        x20 * GET_J_D(5, 2) + x21 * GET_J_D(5, 3) +
        x23 * GET_J_D(5, 4) +
        GET_C_D(0, 5) * GET_J_D(3, 0) +
        GET_C_D(1, 5) * GET_J_D(3, 1) +
        GET_C_D(2, 5) * GET_J_D(3, 2) +
        GET_C_D(3, 5) * GET_J_D(3, 3) +
        GET_C_D(4, 5) * GET_J_D(3, 4));
    getter::element(new_C, 4u, 5u) = static_cast<scalar_t>(
        x24 + GET_C_D(4, 0) * GET_J_D(5, 0) +
        GET_C_D(4, 1) * GET_J_D(5, 1) +
        GET_C_D(4, 2) * GET_J_D(5, 2) +
        GET_C_D(4, 3) * GET_J_D(5, 3) +
        GET_C_D(4, 5));
    getter::element(new_C, 5u, 5u) = static_cast<scalar_t>(
        x25 * GET_J_D(5, 0) + x26 * GET_J_D(5, 1) +
        x27 * GET_J_D(5, 2) + x28 * GET_J_D(5, 3) +
        x29 * GET_J_D(5, 4) +
        GET_C_D(0, 5) * GET_J_D(5, 0) +
        GET_C_D(1, 5) * GET_J_D(5, 1) +
        GET_C_D(2, 5) * GET_J_D(5, 2) +
        GET_C_D(3, 5) * GET_J_D(5, 3) +
        GET_C_D(4, 5) * GET_J_D(5, 4) +
        GET_C_D(5, 5));

    #undef GET_C_D
    #undef GET_J_D
}

#else  // !DETRAY_MIXED_PRECISION_COVARIANCE

// Original single-precision version
template <typename jac_matrix_t, typename cov_matrix_t>
DETRAY_HOST_DEVICE void inline transport_covariance_to_bound_impl(
    const cov_matrix_t& C, const jac_matrix_t& J_full, cov_matrix_t& new_C) {
    const auto x4 =
        getter::element(C, 4u, 4u) * getter::element(J_full, 0u, 4u);
    const auto x10 =
        getter::element(C, 4u, 4u) * getter::element(J_full, 1u, 4u);
    const auto x16 =
        getter::element(C, 4u, 4u) * getter::element(J_full, 2u, 4u);
    const auto x22 =
        getter::element(C, 4u, 4u) * getter::element(J_full, 3u, 4u);
    const auto x24 =
        getter::element(C, 4u, 4u) * getter::element(J_full, 5u, 4u);
    const auto x0 =
        getter::element(C, 0u, 0u) * getter::element(J_full, 0u, 0u) +
        getter::element(C, 1u, 0u) * getter::element(J_full, 0u, 1u) +
        getter::element(C, 2u, 0u) * getter::element(J_full, 0u, 2u) +
        getter::element(C, 3u, 0u) * getter::element(J_full, 0u, 3u) +
        getter::element(C, 4u, 0u) * getter::element(J_full, 0u, 4u);
    const auto x1 =
        getter::element(C, 0u, 1u) * getter::element(J_full, 0u, 0u) +
        getter::element(C, 1u, 1u) * getter::element(J_full, 0u, 1u) +
        getter::element(C, 2u, 1u) * getter::element(J_full, 0u, 2u) +
        getter::element(C, 3u, 1u) * getter::element(J_full, 0u, 3u) +
        getter::element(C, 4u, 1u) * getter::element(J_full, 0u, 4u);
    const auto x2 =
        getter::element(C, 0u, 2u) * getter::element(J_full, 0u, 0u) +
        getter::element(C, 1u, 2u) * getter::element(J_full, 0u, 1u) +
        getter::element(C, 2u, 2u) * getter::element(J_full, 0u, 2u) +
        getter::element(C, 3u, 2u) * getter::element(J_full, 0u, 3u) +
        getter::element(C, 4u, 2u) * getter::element(J_full, 0u, 4u);
    const auto x3 =
        getter::element(C, 0u, 3u) * getter::element(J_full, 0u, 0u) +
        getter::element(C, 1u, 3u) * getter::element(J_full, 0u, 1u) +
        getter::element(C, 2u, 3u) * getter::element(J_full, 0u, 2u) +
        getter::element(C, 3u, 3u) * getter::element(J_full, 0u, 3u) +
        getter::element(C, 4u, 3u) * getter::element(J_full, 0u, 4u);
    const auto x6 =
        getter::element(C, 0u, 0u) * getter::element(J_full, 1u, 0u) +
        getter::element(C, 1u, 0u) * getter::element(J_full, 1u, 1u) +
        getter::element(C, 2u, 0u) * getter::element(J_full, 1u, 2u) +
        getter::element(C, 3u, 0u) * getter::element(J_full, 1u, 3u) +
        getter::element(C, 4u, 0u) * getter::element(J_full, 1u, 4u);
    const auto x7 =
        getter::element(C, 0u, 1u) * getter::element(J_full, 1u, 0u) +
        getter::element(C, 1u, 1u) * getter::element(J_full, 1u, 1u) +
        getter::element(C, 2u, 1u) * getter::element(J_full, 1u, 2u) +
        getter::element(C, 3u, 1u) * getter::element(J_full, 1u, 3u) +
        getter::element(C, 4u, 1u) * getter::element(J_full, 1u, 4u);
    const auto x8 =
        getter::element(C, 0u, 2u) * getter::element(J_full, 1u, 0u) +
        getter::element(C, 1u, 2u) * getter::element(J_full, 1u, 1u) +
        getter::element(C, 2u, 2u) * getter::element(J_full, 1u, 2u) +
        getter::element(C, 3u, 2u) * getter::element(J_full, 1u, 3u) +
        getter::element(C, 4u, 2u) * getter::element(J_full, 1u, 4u);
    const auto x9 =
        getter::element(C, 0u, 3u) * getter::element(J_full, 1u, 0u) +
        getter::element(C, 1u, 3u) * getter::element(J_full, 1u, 1u) +
        getter::element(C, 2u, 3u) * getter::element(J_full, 1u, 2u) +
        getter::element(C, 3u, 3u) * getter::element(J_full, 1u, 3u) +
        getter::element(C, 4u, 3u) * getter::element(J_full, 1u, 4u);
    const auto x12 =
        getter::element(C, 0u, 0u) * getter::element(J_full, 2u, 0u) +
        getter::element(C, 1u, 0u) * getter::element(J_full, 2u, 1u) +
        getter::element(C, 2u, 0u) * getter::element(J_full, 2u, 2u) +
        getter::element(C, 3u, 0u) * getter::element(J_full, 2u, 3u) +
        getter::element(C, 4u, 0u) * getter::element(J_full, 2u, 4u);
    const auto x13 =
        getter::element(C, 0u, 1u) * getter::element(J_full, 2u, 0u) +
        getter::element(C, 1u, 1u) * getter::element(J_full, 2u, 1u) +
        getter::element(C, 2u, 1u) * getter::element(J_full, 2u, 2u) +
        getter::element(C, 3u, 1u) * getter::element(J_full, 2u, 3u) +
        getter::element(C, 4u, 1u) * getter::element(J_full, 2u, 4u);
    const auto x14 =
        getter::element(C, 0u, 2u) * getter::element(J_full, 2u, 0u) +
        getter::element(C, 1u, 2u) * getter::element(J_full, 2u, 1u) +
        getter::element(C, 2u, 2u) * getter::element(J_full, 2u, 2u) +
        getter::element(C, 3u, 2u) * getter::element(J_full, 2u, 3u) +
        getter::element(C, 4u, 2u) * getter::element(J_full, 2u, 4u);
    const auto x15 =
        getter::element(C, 0u, 3u) * getter::element(J_full, 2u, 0u) +
        getter::element(C, 1u, 3u) * getter::element(J_full, 2u, 1u) +
        getter::element(C, 2u, 3u) * getter::element(J_full, 2u, 2u) +
        getter::element(C, 3u, 3u) * getter::element(J_full, 2u, 3u) +
        getter::element(C, 4u, 3u) * getter::element(J_full, 2u, 4u);
    const auto x18 =
        getter::element(C, 0u, 0u) * getter::element(J_full, 3u, 0u) +
        getter::element(C, 1u, 0u) * getter::element(J_full, 3u, 1u) +
        getter::element(C, 2u, 0u) * getter::element(J_full, 3u, 2u) +
        getter::element(C, 3u, 0u) * getter::element(J_full, 3u, 3u) +
        getter::element(C, 4u, 0u) * getter::element(J_full, 3u, 4u);
    const auto x19 =
        getter::element(C, 0u, 1u) * getter::element(J_full, 3u, 0u) +
        getter::element(C, 1u, 1u) * getter::element(J_full, 3u, 1u) +
        getter::element(C, 2u, 1u) * getter::element(J_full, 3u, 2u) +
        getter::element(C, 3u, 1u) * getter::element(J_full, 3u, 3u) +
        getter::element(C, 4u, 1u) * getter::element(J_full, 3u, 4u);
    const auto x20 =
        getter::element(C, 0u, 2u) * getter::element(J_full, 3u, 0u) +
        getter::element(C, 1u, 2u) * getter::element(J_full, 3u, 1u) +
        getter::element(C, 2u, 2u) * getter::element(J_full, 3u, 2u) +
        getter::element(C, 3u, 2u) * getter::element(J_full, 3u, 3u) +
        getter::element(C, 4u, 2u) * getter::element(J_full, 3u, 4u);
    const auto x21 =
        getter::element(C, 0u, 3u) * getter::element(J_full, 3u, 0u) +
        getter::element(C, 1u, 3u) * getter::element(J_full, 3u, 1u) +
        getter::element(C, 2u, 3u) * getter::element(J_full, 3u, 2u) +
        getter::element(C, 3u, 3u) * getter::element(J_full, 3u, 3u) +
        getter::element(C, 4u, 3u) * getter::element(J_full, 3u, 4u);
    const auto x25 =
        getter::element(C, 0u, 0u) * getter::element(J_full, 5u, 0u) +
        getter::element(C, 1u, 0u) * getter::element(J_full, 5u, 1u) +
        getter::element(C, 2u, 0u) * getter::element(J_full, 5u, 2u) +
        getter::element(C, 3u, 0u) * getter::element(J_full, 5u, 3u) +
        getter::element(C, 4u, 0u) * getter::element(J_full, 5u, 4u) +
        getter::element(C, 5u, 0u);
    const auto x26 =
        getter::element(C, 0u, 1u) * getter::element(J_full, 5u, 0u) +
        getter::element(C, 1u, 1u) * getter::element(J_full, 5u, 1u) +
        getter::element(C, 2u, 1u) * getter::element(J_full, 5u, 2u) +
        getter::element(C, 3u, 1u) * getter::element(J_full, 5u, 3u) +
        getter::element(C, 4u, 1u) * getter::element(J_full, 5u, 4u) +
        getter::element(C, 5u, 1u);
    const auto x27 =
        getter::element(C, 0u, 2u) * getter::element(J_full, 5u, 0u) +
        getter::element(C, 1u, 2u) * getter::element(J_full, 5u, 1u) +
        getter::element(C, 2u, 2u) * getter::element(J_full, 5u, 2u) +
        getter::element(C, 3u, 2u) * getter::element(J_full, 5u, 3u) +
        getter::element(C, 4u, 2u) * getter::element(J_full, 5u, 4u) +
        getter::element(C, 5u, 2u);
    const auto x28 =
        getter::element(C, 0u, 3u) * getter::element(J_full, 5u, 0u) +
        getter::element(C, 1u, 3u) * getter::element(J_full, 5u, 1u) +
        getter::element(C, 2u, 3u) * getter::element(J_full, 5u, 2u) +
        getter::element(C, 3u, 3u) * getter::element(J_full, 5u, 3u) +
        getter::element(C, 4u, 3u) * getter::element(J_full, 5u, 4u) +
        getter::element(C, 5u, 3u);
    const auto x5 =
        x4 + getter::element(C, 0u, 4u) * getter::element(J_full, 0u, 0u) +
        getter::element(C, 1u, 4u) * getter::element(J_full, 0u, 1u) +
        getter::element(C, 2u, 4u) * getter::element(J_full, 0u, 2u) +
        getter::element(C, 3u, 4u) * getter::element(J_full, 0u, 3u);
    const auto x11 =
        x10 + getter::element(C, 0u, 4u) * getter::element(J_full, 1u, 0u) +
        getter::element(C, 1u, 4u) * getter::element(J_full, 1u, 1u) +
        getter::element(C, 2u, 4u) * getter::element(J_full, 1u, 2u) +
        getter::element(C, 3u, 4u) * getter::element(J_full, 1u, 3u);
    const auto x17 =
        x16 + getter::element(C, 0u, 4u) * getter::element(J_full, 2u, 0u) +
        getter::element(C, 1u, 4u) * getter::element(J_full, 2u, 1u) +
        getter::element(C, 2u, 4u) * getter::element(J_full, 2u, 2u) +
        getter::element(C, 3u, 4u) * getter::element(J_full, 2u, 3u);
    const auto x23 =
        x22 + getter::element(C, 0u, 4u) * getter::element(J_full, 3u, 0u) +
        getter::element(C, 1u, 4u) * getter::element(J_full, 3u, 1u) +
        getter::element(C, 2u, 4u) * getter::element(J_full, 3u, 2u) +
        getter::element(C, 3u, 4u) * getter::element(J_full, 3u, 3u);
    const auto x29 =
        x24 + getter::element(C, 0u, 4u) * getter::element(J_full, 5u, 0u) +
        getter::element(C, 1u, 4u) * getter::element(J_full, 5u, 1u) +
        getter::element(C, 2u, 4u) * getter::element(J_full, 5u, 2u) +
        getter::element(C, 3u, 4u) * getter::element(J_full, 5u, 3u) +
        getter::element(C, 5u, 4u);
    getter::element(new_C, 0u, 0u) = x0 * getter::element(J_full, 0u, 0u) +
                                     x1 * getter::element(J_full, 0u, 1u) +
                                     x2 * getter::element(J_full, 0u, 2u) +
                                     x3 * getter::element(J_full, 0u, 3u) +
                                     x5 * getter::element(J_full, 0u, 4u);
    getter::element(new_C, 1u, 0u) = x11 * getter::element(J_full, 0u, 4u) +
                                     x6 * getter::element(J_full, 0u, 0u) +
                                     x7 * getter::element(J_full, 0u, 1u) +
                                     x8 * getter::element(J_full, 0u, 2u) +
                                     x9 * getter::element(J_full, 0u, 3u);
    getter::element(new_C, 2u, 0u) = x12 * getter::element(J_full, 0u, 0u) +
                                     x13 * getter::element(J_full, 0u, 1u) +
                                     x14 * getter::element(J_full, 0u, 2u) +
                                     x15 * getter::element(J_full, 0u, 3u) +
                                     x17 * getter::element(J_full, 0u, 4u);
    getter::element(new_C, 3u, 0u) = x18 * getter::element(J_full, 0u, 0u) +
                                     x19 * getter::element(J_full, 0u, 1u) +
                                     x20 * getter::element(J_full, 0u, 2u) +
                                     x21 * getter::element(J_full, 0u, 3u) +
                                     x23 * getter::element(J_full, 0u, 4u);
    getter::element(new_C, 4u, 0u) =
        x4 + getter::element(C, 4u, 0u) * getter::element(J_full, 0u, 0u) +
        getter::element(C, 4u, 1u) * getter::element(J_full, 0u, 1u) +
        getter::element(C, 4u, 2u) * getter::element(J_full, 0u, 2u) +
        getter::element(C, 4u, 3u) * getter::element(J_full, 0u, 3u);
    getter::element(new_C, 5u, 0u) = x25 * getter::element(J_full, 0u, 0u) +
                                     x26 * getter::element(J_full, 0u, 1u) +
                                     x27 * getter::element(J_full, 0u, 2u) +
                                     x28 * getter::element(J_full, 0u, 3u) +
                                     x29 * getter::element(J_full, 0u, 4u);
    getter::element(new_C, 0u, 1u) = x0 * getter::element(J_full, 1u, 0u) +
                                     x1 * getter::element(J_full, 1u, 1u) +
                                     x2 * getter::element(J_full, 1u, 2u) +
                                     x3 * getter::element(J_full, 1u, 3u) +
                                     x5 * getter::element(J_full, 1u, 4u);
    getter::element(new_C, 1u, 1u) = x11 * getter::element(J_full, 1u, 4u) +
                                     x6 * getter::element(J_full, 1u, 0u) +
                                     x7 * getter::element(J_full, 1u, 1u) +
                                     x8 * getter::element(J_full, 1u, 2u) +
                                     x9 * getter::element(J_full, 1u, 3u);
    getter::element(new_C, 2u, 1u) = x12 * getter::element(J_full, 1u, 0u) +
                                     x13 * getter::element(J_full, 1u, 1u) +
                                     x14 * getter::element(J_full, 1u, 2u) +
                                     x15 * getter::element(J_full, 1u, 3u) +
                                     x17 * getter::element(J_full, 1u, 4u);
    getter::element(new_C, 3u, 1u) = x18 * getter::element(J_full, 1u, 0u) +
                                     x19 * getter::element(J_full, 1u, 1u) +
                                     x20 * getter::element(J_full, 1u, 2u) +
                                     x21 * getter::element(J_full, 1u, 3u) +
                                     x23 * getter::element(J_full, 1u, 4u);
    getter::element(new_C, 4u, 1u) =
        x10 + getter::element(C, 4u, 0u) * getter::element(J_full, 1u, 0u) +
        getter::element(C, 4u, 1u) * getter::element(J_full, 1u, 1u) +
        getter::element(C, 4u, 2u) * getter::element(J_full, 1u, 2u) +
        getter::element(C, 4u, 3u) * getter::element(J_full, 1u, 3u);
    getter::element(new_C, 5u, 1u) = x25 * getter::element(J_full, 1u, 0u) +
                                     x26 * getter::element(J_full, 1u, 1u) +
                                     x27 * getter::element(J_full, 1u, 2u) +
                                     x28 * getter::element(J_full, 1u, 3u) +
                                     x29 * getter::element(J_full, 1u, 4u);
    getter::element(new_C, 0u, 2u) = x0 * getter::element(J_full, 2u, 0u) +
                                     x1 * getter::element(J_full, 2u, 1u) +
                                     x2 * getter::element(J_full, 2u, 2u) +
                                     x3 * getter::element(J_full, 2u, 3u) +
                                     x5 * getter::element(J_full, 2u, 4u);
    getter::element(new_C, 1u, 2u) = x11 * getter::element(J_full, 2u, 4u) +
                                     x6 * getter::element(J_full, 2u, 0u) +
                                     x7 * getter::element(J_full, 2u, 1u) +
                                     x8 * getter::element(J_full, 2u, 2u) +
                                     x9 * getter::element(J_full, 2u, 3u);
    getter::element(new_C, 2u, 2u) = x12 * getter::element(J_full, 2u, 0u) +
                                     x13 * getter::element(J_full, 2u, 1u) +
                                     x14 * getter::element(J_full, 2u, 2u) +
                                     x15 * getter::element(J_full, 2u, 3u) +
                                     x17 * getter::element(J_full, 2u, 4u);
    getter::element(new_C, 3u, 2u) = x18 * getter::element(J_full, 2u, 0u) +
                                     x19 * getter::element(J_full, 2u, 1u) +
                                     x20 * getter::element(J_full, 2u, 2u) +
                                     x21 * getter::element(J_full, 2u, 3u) +
                                     x23 * getter::element(J_full, 2u, 4u);
    getter::element(new_C, 4u, 2u) =
        x16 + getter::element(C, 4u, 0u) * getter::element(J_full, 2u, 0u) +
        getter::element(C, 4u, 1u) * getter::element(J_full, 2u, 1u) +
        getter::element(C, 4u, 2u) * getter::element(J_full, 2u, 2u) +
        getter::element(C, 4u, 3u) * getter::element(J_full, 2u, 3u);
    getter::element(new_C, 5u, 2u) = x25 * getter::element(J_full, 2u, 0u) +
                                     x26 * getter::element(J_full, 2u, 1u) +
                                     x27 * getter::element(J_full, 2u, 2u) +
                                     x28 * getter::element(J_full, 2u, 3u) +
                                     x29 * getter::element(J_full, 2u, 4u);
    getter::element(new_C, 0u, 3u) = x0 * getter::element(J_full, 3u, 0u) +
                                     x1 * getter::element(J_full, 3u, 1u) +
                                     x2 * getter::element(J_full, 3u, 2u) +
                                     x3 * getter::element(J_full, 3u, 3u) +
                                     x5 * getter::element(J_full, 3u, 4u);
    getter::element(new_C, 1u, 3u) = x11 * getter::element(J_full, 3u, 4u) +
                                     x6 * getter::element(J_full, 3u, 0u) +
                                     x7 * getter::element(J_full, 3u, 1u) +
                                     x8 * getter::element(J_full, 3u, 2u) +
                                     x9 * getter::element(J_full, 3u, 3u);
    getter::element(new_C, 2u, 3u) = x12 * getter::element(J_full, 3u, 0u) +
                                     x13 * getter::element(J_full, 3u, 1u) +
                                     x14 * getter::element(J_full, 3u, 2u) +
                                     x15 * getter::element(J_full, 3u, 3u) +
                                     x17 * getter::element(J_full, 3u, 4u);
    getter::element(new_C, 3u, 3u) = x18 * getter::element(J_full, 3u, 0u) +
                                     x19 * getter::element(J_full, 3u, 1u) +
                                     x20 * getter::element(J_full, 3u, 2u) +
                                     x21 * getter::element(J_full, 3u, 3u) +
                                     x23 * getter::element(J_full, 3u, 4u);
    getter::element(new_C, 4u, 3u) =
        x22 + getter::element(C, 4u, 0u) * getter::element(J_full, 3u, 0u) +
        getter::element(C, 4u, 1u) * getter::element(J_full, 3u, 1u) +
        getter::element(C, 4u, 2u) * getter::element(J_full, 3u, 2u) +
        getter::element(C, 4u, 3u) * getter::element(J_full, 3u, 3u);
    getter::element(new_C, 5u, 3u) = x25 * getter::element(J_full, 3u, 0u) +
                                     x26 * getter::element(J_full, 3u, 1u) +
                                     x27 * getter::element(J_full, 3u, 2u) +
                                     x28 * getter::element(J_full, 3u, 3u) +
                                     x29 * getter::element(J_full, 3u, 4u);
    getter::element(new_C, 0u, 4u) = x5;
    getter::element(new_C, 1u, 4u) = x11;
    getter::element(new_C, 2u, 4u) = x17;
    getter::element(new_C, 3u, 4u) = x23;
    getter::element(new_C, 4u, 4u) = getter::element(C, 4u, 4u);
    getter::element(new_C, 5u, 4u) = x29;
    getter::element(new_C, 0u, 5u) =
        x0 * getter::element(J_full, 5u, 0u) +
        x1 * getter::element(J_full, 5u, 1u) +
        x2 * getter::element(J_full, 5u, 2u) +
        x3 * getter::element(J_full, 5u, 3u) +
        x5 * getter::element(J_full, 5u, 4u) +
        getter::element(C, 0u, 5u) * getter::element(J_full, 0u, 0u) +
        getter::element(C, 1u, 5u) * getter::element(J_full, 0u, 1u) +
        getter::element(C, 2u, 5u) * getter::element(J_full, 0u, 2u) +
        getter::element(C, 3u, 5u) * getter::element(J_full, 0u, 3u) +
        getter::element(C, 4u, 5u) * getter::element(J_full, 0u, 4u);
    getter::element(new_C, 1u, 5u) =
        x11 * getter::element(J_full, 5u, 4u) +
        x6 * getter::element(J_full, 5u, 0u) +
        x7 * getter::element(J_full, 5u, 1u) +
        x8 * getter::element(J_full, 5u, 2u) +
        x9 * getter::element(J_full, 5u, 3u) +
        getter::element(C, 0u, 5u) * getter::element(J_full, 1u, 0u) +
        getter::element(C, 1u, 5u) * getter::element(J_full, 1u, 1u) +
        getter::element(C, 2u, 5u) * getter::element(J_full, 1u, 2u) +
        getter::element(C, 3u, 5u) * getter::element(J_full, 1u, 3u) +
        getter::element(C, 4u, 5u) * getter::element(J_full, 1u, 4u);
    getter::element(new_C, 2u, 5u) =
        x12 * getter::element(J_full, 5u, 0u) +
        x13 * getter::element(J_full, 5u, 1u) +
        x14 * getter::element(J_full, 5u, 2u) +
        x15 * getter::element(J_full, 5u, 3u) +
        x17 * getter::element(J_full, 5u, 4u) +
        getter::element(C, 0u, 5u) * getter::element(J_full, 2u, 0u) +
        getter::element(C, 1u, 5u) * getter::element(J_full, 2u, 1u) +
        getter::element(C, 2u, 5u) * getter::element(J_full, 2u, 2u) +
        getter::element(C, 3u, 5u) * getter::element(J_full, 2u, 3u) +
        getter::element(C, 4u, 5u) * getter::element(J_full, 2u, 4u);
    getter::element(new_C, 3u, 5u) =
        x18 * getter::element(J_full, 5u, 0u) +
        x19 * getter::element(J_full, 5u, 1u) +
        x20 * getter::element(J_full, 5u, 2u) +
        x21 * getter::element(J_full, 5u, 3u) +
        x23 * getter::element(J_full, 5u, 4u) +
        getter::element(C, 0u, 5u) * getter::element(J_full, 3u, 0u) +
        getter::element(C, 1u, 5u) * getter::element(J_full, 3u, 1u) +
        getter::element(C, 2u, 5u) * getter::element(J_full, 3u, 2u) +
        getter::element(C, 3u, 5u) * getter::element(J_full, 3u, 3u) +
        getter::element(C, 4u, 5u) * getter::element(J_full, 3u, 4u);
    getter::element(new_C, 4u, 5u) =
        x24 + getter::element(C, 4u, 0u) * getter::element(J_full, 5u, 0u) +
        getter::element(C, 4u, 1u) * getter::element(J_full, 5u, 1u) +
        getter::element(C, 4u, 2u) * getter::element(J_full, 5u, 2u) +
        getter::element(C, 4u, 3u) * getter::element(J_full, 5u, 3u) +
        getter::element(C, 4u, 5u);
    getter::element(new_C, 5u, 5u) =
        x25 * getter::element(J_full, 5u, 0u) +
        x26 * getter::element(J_full, 5u, 1u) +
        x27 * getter::element(J_full, 5u, 2u) +
        x28 * getter::element(J_full, 5u, 3u) +
        x29 * getter::element(J_full, 5u, 4u) +
        getter::element(C, 0u, 5u) * getter::element(J_full, 5u, 0u) +
        getter::element(C, 1u, 5u) * getter::element(J_full, 5u, 1u) +
        getter::element(C, 2u, 5u) * getter::element(J_full, 5u, 2u) +
        getter::element(C, 3u, 5u) * getter::element(J_full, 5u, 3u) +
        getter::element(C, 4u, 5u) * getter::element(J_full, 5u, 4u) +
        getter::element(C, 5u, 5u);
}

#endif  // DETRAY_MIXED_PRECISION_COVARIANCE

}  // namespace detray::detail
